'use client';

import React from 'react';
import { Badge, Panel, SectionGroup } from '../Shared';
import { toneForStatus } from '../../../lib/command-center/utils';
import type { AskResponse } from '../../../lib/command-center/types';
import type { IntelligenceReport } from '../../../lib/types';

export function AskHub({ question, setQuestion, askHub, askResponse, busy, currentReport }: { question: string; setQuestion: (value: string) => void; askHub: () => void; askResponse: AskResponse | null; busy: boolean; currentReport: IntelligenceReport | null }) {
  return <><section className="section"><div><h1>Ask the Hub</h1><p className="text-body">Ask plain English questions against the latest stored intelligence report and get ranked evidence, safe language, and recommended next moves.</p></div><Badge tone={currentReport ? 'green' : 'amber'}>{currentReport ? 'Report loaded' : 'No report loaded'}</Badge></section><Panel title="Ask a competitive question"><textarea className="textarea largeInput" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What should I lead with against this competitor?" /><button className="btn primary" disabled={busy || !question.trim()} onClick={askHub} style={{ marginTop: '8px' }}>Ask the Hub</button></Panel>{askResponse ? <section className="hero answerHero"><div className="row spread" style={{ marginBottom: '8px' }}><h2 style={{ margin: 0 }}>Answer</h2><Badge tone={toneForStatus(askResponse.confidence)}>{askResponse.confidence}</Badge></div><p className="text-body">{askResponse.answer}</p>{askResponse.questionTerms?.length ? <div className="tagCloud lightTags" style={{ marginTop: '8px' }}>{askResponse.questionTerms.map((term) => <span key={term}>{term}</span>)}</div> : null}</section> : null}{askResponse?.nextBestActions?.length ? <SectionGroup title="Recommended next moves"><div className="briefList">{askResponse.nextBestActions.map((action, i) => <div className="briefItem hover-card" key={i} style={{ padding: '12px', display: 'flex', alignItems: 'flex-start', gap: '8px' }}><Badge tone="blue">Action</Badge><span className="text-small" style={{ color: 'var(--color-text-secondary)' }}>{action}</span></div>)}</div></SectionGroup> : null}{askResponse?.evidence?.length ? <SectionGroup title={`Ranked evidence (${askResponse.evidence.length} items)`}><div className="grid cols2">{askResponse.evidence.slice(0, 8).map((item, index) => <div className="evidenceCard hover-card" key={`${item.competitorName}${item.serviceLine}${item.subservice}${index}`} style={{ padding: '16px' }}><div className="row spread" style={{ marginBottom: '6px' }}><Badge tone="dark">Score {item.smartScore || 0}</Badge><Badge tone={toneForStatus(item.status)}>{item.status}</Badge></div><h3 className="text-subhead" style={{ margin: '0 0 4px' }}>{item.competitorName}</h3><p className="text-small" style={{ margin: '0 0 4px' }}><strong>{item.serviceLine}</strong>{item.subservice ? ` | ${item.subservice}` : ''}</p><p className="text-small" style={{ color: 'var(--color-text-secondary)' }}>{item.evidenceExcerpt}</p><div className="notice" style={{ fontSize: '12px', padding: '8px', marginTop: '6px' }}><strong>Safe wording</strong><br />{item.safeSalesWording}</div>{item.recommendedAction ? <div className="error" style={{ fontSize: '12px', padding: '8px', marginTop: '6px' }}><strong>Action</strong><br />{item.recommendedAction}</div> : null}</div>)}</div></SectionGroup> : null}</>;
}
