'use client';

import React from 'react';
import { Badge, Panel, TagList, ExpandableSection, SectionGroup } from '../Shared';
import { toneForStatus } from '../../../lib/command-center/utils';
import type { View } from '../../../lib/command-center/types';
import type { IntelligenceReport } from '../../../lib/types';

export function ExpertCenter({ currentReport, setView }: { currentReport: IntelligenceReport | null; setView: (view: View) => void }) {
  const expert = currentReport?.expertBrief;
  if (!currentReport) return <Panel title="No report loaded"><p className="text-body">Run or load a report to generate the foremost expert brief.</p><button className="btn primary" style={{ marginTop: '12px' }} onClick={() => setView('intake')}>Run Competitive Scan</button></Panel>;
  if (!expert) return <Panel title="Fresh scan needed"><p className="text-body">This report was created before the foremost expert engine was added. Run a fresh scan to generate expert recommendations, field plays, and watchlist items.</p><button className="btn primary" style={{ marginTop: '12px' }} onClick={() => setView('intake')}>Run Fresh Scan</button></Panel>;
  return <>
    <section className="hero answerHero"><div className="row spread" style={{ marginBottom: '8px' }}><Badge tone="dark">{expert.expertVersion}</Badge><Badge tone={expert.expertScore >= 80 ? 'green' : expert.expertScore >= 60 ? 'amber' : 'blue'}>Expert score {expert.expertScore}</Badge></div><h1>{expert.marketPosture}</h1><p className="text-body">{expert.expertSummary}</p><div className="row" style={{ gap: '8px' }}><button className="btn" onClick={() => setView('battlecards')}>Open Battlecards</button><button className="btn" onClick={() => setView('matrix')}>Review Evidence</button><button className="btn" onClick={() => setView('ask')}>Ask Follow Up</button></div></section>
    <SectionGroup title="Core positions"><div className="grid cols3"><Panel title="Leadership decision"><p className="text-small">{expert.leadershipDecision}</p></Panel><Panel title="Sales coaching priority"><p className="text-small">{expert.salesCoachingPriority}</p></Panel><Panel title="Fastest field move"><p className="text-small">{expert.fastestFieldMove}</p></Panel></div></SectionGroup>
    <Panel title="Governance warning" className="featurePanel"><p className="text-small">{expert.governanceWarning}</p></Panel>
    <SectionGroup title="Expert recommendations"><div className="grid cols2">{expert.recommendations.map((item) => <div className="briefItem hover-card" key={item.id} style={{ padding: '14px' }}><div className="row spread" style={{ marginBottom: '6px' }}><Badge tone={toneForStatus(item.priority)}>{item.priority}</Badge><Badge>{item.audience}</Badge></div><strong className="text-subhead" style={{ display: 'block', marginBottom: '4px' }}>{item.title}</strong><p className="text-small" style={{ margin: '4px 0', color: 'var(--color-text-secondary)' }}>{item.reasoning}</p><ExpandableSection title="Action details" defaultOpen><div className="success" style={{ padding: '10px', fontSize: '13px', marginBottom: '8px' }}><strong>Action</strong><br />{item.action}</div><div className="notice" style={{ padding: '10px', fontSize: '13px' }}><strong>Safe language</strong><br />{item.safeLanguage}</div>{item.reviewRequired ? <Badge tone="amber">Review required</Badge> : <Badge tone="green">Ready for coaching</Badge>}</ExpandableSection></div>)}</div></SectionGroup>
    <SectionGroup title="Field plays"><div className="grid cols2">{expert.fieldPlays.map((play) => <div className="battleCard upgradedBattle hover-card" key={play.id}><div className="row spread" style={{ marginBottom: '8px' }}><h3 className="text-heading" style={{ margin: 0 }}>{play.competitorName}</h3><Badge>{play.serviceLine}</Badge></div><p className="text-small" style={{ color: 'var(--color-text-secondary)' }}>{play.scenario}</p><ExpandableSection title="Play details"><div className="battleSection"><strong>Lead with</strong><span style={{ display: 'block', marginTop: '4px' }}>{play.leadWith}</span></div><div className="battleSection" style={{ marginTop: '8px' }}><strong>Referral question</strong><span style={{ display: 'block', marginTop: '4px' }}>{play.referralQuestion}</span></div><div className="battleSection" style={{ marginTop: '8px' }}><strong>Objection response</strong><span style={{ display: 'block', marginTop: '4px' }}>{play.objectionResponse}</span></div><div className="notice" style={{ marginTop: '8px', fontSize: '13px' }}><strong>Proof needed</strong><br />{play.proofNeeded}</div><div className="error" style={{ marginTop: '8px', fontSize: '13px' }}><strong>Avoid saying</strong><br />{play.avoidSaying}</div></ExpandableSection></div>)}</div></SectionGroup>
    <div className="grid cols2"><Panel title="Strongest threats"><TagList items={expert.strongestThreats} /></Panel><Panel title="Best opportunities"><TagList items={expert.bestOpportunities} /></Panel></div>
    <SectionGroup title="Watchlist"><div className="grid cols2">{expert.watchlist.map((item) => <div className="evidenceCard hover-card" key={item.id} style={{ padding: '16px' }}><div className="row spread" style={{ marginBottom: '6px' }}><h3 className="text-subhead" style={{ margin: 0 }}>{item.competitorName}</h3><Badge tone={toneForStatus(item.priority)}>{item.priority}</Badge></div><p className="text-small"><strong>Signal:</strong> {item.signal}</p><p className="text-small" style={{ color: 'var(--color-text-secondary)' }}>{item.whyItMatters}</p><div className="notice" style={{ fontSize: '13px', padding: '10px' }}><strong>Next check</strong><br />{item.nextCheck}</div></div>)}</div></SectionGroup>
  </>;
}
